### ISSUE TITLE
Use custom logo/header/theme

### ISSUE THREAD

**Issue by Carlosmape** [startup-nvim/startup.nvim#31]
I am trying to use a custom header/logo. I want to make it "persistent", I mean: I use nvim with the same configuration in multiple (cross-platform) computers (personal one running linux and work one running windows). I often use my own nvim-config repository to keep both synced. As I can understand, to customize this plugin header/logo/theme or whatever, you MUST place it inside nvim binaries forlder (see these references: https://neovim.discourse.group/t/require-files-not-from-lua-folder/1823/9) to properly require it before from Lua...
So what I am trying to do is (I have copied entire Dashboard theme to "*nvim_config_folder*/dashboard/custom.lua") and then adding this pattern to Lua's require one like suggested the link before:
``` lua
--Startup configuration, custom Dashboard
local dashboard_path = vim.fn.stdpath 'config' .. '/?.lua;'
package.path = dashboard_path .. package.path
require("startup").setup({require("dashboard.custom")})
```
But it throws the next error when nvim opens:
![imagen](https://user-images.githubusercontent.com/5487555/179522756-5b6951d2-4bfd-42c2-b37a-c5e2e9ef77d1.png)

I think the error comes due to change this "require" pattern

It would be a nice idea to have a function/variable to configure it (without having to create/modify own theme or sample ones)

**Comment by max397574** [comment]
you have to put the `dashboard/custom.lua` file into the `lua` directory in your config folder

**Comment by max397574** [comment]
I missread something there
1. why do you think you need to put it into "nvim binaries" folder. What should that even be? Never heard about anything like that. You just need to put it into the `lua` folder inside your config  (read [lua guide](https://neovim.io/doc/user/lua-guide.html#lua-guide) to understand lua modules)
2. the errors seems like there is a problem in your custom theme. Can you send it?

**Comment by Carlosmape** [comment]
I mean to have a lua file justo containing headers (to do not extend my "startup.lua" file too much. I finally solve ir by declaring headers directly un the configuration one

**Comment by max397574** [comment]
so this issue is fixed?

**Comment by Carlosmape** [comment]
Not fixed, but I think it could be closed. The solución un muy case was to define headers in the sale lua file as the config
